services:
  api:
    build: .
    ports:
      - "5000:5000" 
    volumes:
      - .:/usr/src/app 
    environment:
      - MONGO_URI=mongodb://mongo-db:27017/minha-if-db
    depends_on:
      - mongo-db
  mongo-db:
    image: mongo:latest
    ports:
      - "27017:27017" 
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: